version: 2

project_name: ignit

builds:
  - env:
      - CGO_ENABLED=0
    # main.go declares `version`; release builds override it here.
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE


aurs:
  - name: ignit-bin
    homepage: https://github.com/rubiin/ignit
    description: Quickly generate .gitignore files for your projects from a curated list of environment templates.
    license: GPL-3.0-only
    maintainers:
      - "rubiin <roobin.bhandari@gmail.com>"
    git_url: ssh://aur@aur.archlinux.org/ignit-bin.git
    private_key: "{{ .Env.AUR_KEY }}"
    provides:
      - ignit
    conflicts:
      - ignit
      - ignit-git
    package: |-
      # bin
      install -Dm755 "./ignit" "${pkgdir}/usr/bin/ignit"
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/ignit/LICENSE"

nfpms:
  - package_name: ignit
    file_name_template: '{{ .ConventionalFileName }}'
    homepage: https://github.com/rubiin/ignit
    description: Quickly generate .gitignore files for your projects from a curated list of environment templates.
    license: GPL-3.0-only
    maintainer: rubiin <roobin.bhandari@gmail.com>
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: ./LICENSE
        dst: /usr/share/licenses/ignit/LICENSE

changelog:
  sort: desc
  use: git

  groups:
    - title: 🚀 New Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?(fix|bug)(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
