package main

import (
	"errors"
	"go/parser"
	"go/token"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestParseEnvironmentList(t *testing.T) {
	tests := []struct {
		name string
		body string
		want []string
	}{
		{
			name: "simple list",
			body: "go,rust,python",
			want: []string{"go", "rust", "python"},
		},
		{
			name: "trims whitespace",
			body: " go , rust ,python\n",
			want: []string{"go", "rust", "python"},
		},
		{
			name: "drops empty entries",
			body: "go,,rust,",
			want: []string{"go", "rust"},
		},
		{
			name: "empty body yields nil",
			body: "",
			want: nil,
		},
		{
			name: "whitespace-only body yields nil",
			body: " , , ",
			want: nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := parseEnvironmentList(tt.body)
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("parseEnvironmentList(%q) = %q, want %q", tt.body, got, tt.want)
			}
		})
	}
}

func TestRenderEnvironmentList(t *testing.T) {
	got := renderEnvironmentList([]string{"go", "rust"})

	want := `package main

// Code generated by ` + "`ignit -update-list`" + `. DO NOT EDIT.
// Source: https://www.toptal.com/developers/gitignore/api/list

// environments is a static snapshot of the template list from
// https://github.com/toptal/gitignore.io. The picker works fully
// offline; only writing the .gitignore hits the API.
var environments = []string{
	"go",
	"rust",
}
`
	if got != want {
		t.Errorf("renderEnvironmentList output mismatch:\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestRenderEnvironmentListQuotesSpecialCharacters(t *testing.T) {
	got := renderEnvironmentList([]string{"c++", `back` + "`" + `tick`, "quote\"d"})

	// %q must produce valid Go string literals for tricky names.
	for _, literal := range []string{`"c++"`, "\"back`tick\"", `"quote\"d"`} {
		if !strings.Contains(got, "\t"+literal+",\n") {
			t.Errorf("renderEnvironmentList output missing %s literal:\n%s", literal, got)
		}
	}
}

func TestRenderEnvironmentListOutputParsesAsGo(t *testing.T) {
	src := renderEnvironmentList([]string{"go", "c++", "odd\"name"})

	fset := token.NewFileSet()
	if _, err := parser.ParseFile(fset, "environments.go", src, 0); err != nil {
		t.Fatalf("rendered output does not parse as Go: %v", err)
	}
}

func TestWriteEnvironmentList(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "environments.go")

	content := renderEnvironmentList([]string{"go", "rust"})
	if err := writeEnvironmentList(path, content); err != nil {
		t.Fatalf("writeEnvironmentList() error = %v", err)
	}

	written, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("failed to read written file: %v", err)
	}
	if string(written) != content {
		t.Errorf("written content mismatch:\ngot:\n%s\nwant:\n%s", written, content)
	}
}

func TestWriteEnvironmentListError(t *testing.T) {
	// A directory as target path forces a write error.
	dir := t.TempDir()
	if err := writeEnvironmentList(dir, "package main\n"); err == nil {
		t.Fatal("writeEnvironmentList() expected error when target is a directory, got nil")
	}
}

func TestFetchEnvironmentList(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/list" {
			http.NotFound(w, r)
			return
		}
		w.Write([]byte("go,rust,python"))
	}))
	defer server.Close()

	originalAPI := gitignoreAPI
	gitignoreAPI = server.URL
	defer func() { gitignoreAPI = originalAPI }()

	items, err := fetchEnvironmentList()
	if err != nil {
		t.Fatalf("fetchEnvironmentList() error = %v", err)
	}
	if !reflect.DeepEqual(items, []string{"go", "rust", "python"}) {
		t.Errorf("fetchEnvironmentList() = %q, want [go rust python]", items)
	}
}

func TestFetchEnvironmentListNonOKStatus(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.Error(w, "server error", http.StatusInternalServerError)
	}))
	defer server.Close()

	originalAPI := gitignoreAPI
	gitignoreAPI = server.URL
	defer func() { gitignoreAPI = originalAPI }()

	items, err := fetchEnvironmentList()
	if err == nil {
		t.Fatal("fetchEnvironmentList() expected error for non-200 status, got nil")
	}
	if !strings.Contains(err.Error(), "unexpected status") {
		t.Errorf("fetchEnvironmentList() error = %v, want it to mention unexpected status", err)
	}
	if items != nil {
		t.Errorf("fetchEnvironmentList() items = %q, want nil on error", items)
	}
}

func TestFetchEnvironmentListEmptyBody(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(""))
	}))
	defer server.Close()

	originalAPI := gitignoreAPI
	gitignoreAPI = server.URL
	defer func() { gitignoreAPI = originalAPI }()

	if _, err := fetchEnvironmentList(); err == nil {
		t.Fatal("fetchEnvironmentList() expected error for empty body, got nil")
	}
}

func TestUpdateListEndToEnd(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("go,rust,python"))
	}))
	defer server.Close()

	originalAPI := gitignoreAPI
	gitignoreAPI = server.URL
	defer func() { gitignoreAPI = originalAPI }()

	dir := t.TempDir()
	originalPath := environmentsPath
	environmentsPath = filepath.Join(dir, "environments.go")
	defer func() { environmentsPath = originalPath }()

	if err := updateList(); err != nil {
		t.Fatalf("updateList() error = %v", err)
	}

	written, err := os.ReadFile(environmentsPath)
	if err != nil {
		t.Fatalf("failed to read generated file: %v", err)
	}

	want := renderEnvironmentList([]string{"go", "rust", "python"})
	if string(written) != want {
		t.Errorf("updateList() wrote unexpected content:\ngot:\n%s\nwant:\n%s", written, want)
	}

	// The generated file must parse as valid Go.
	fset := token.NewFileSet()
	if _, err := parser.ParseFile(fset, environmentsPath, written, 0); err != nil {
		t.Fatalf("generated file does not parse as Go: %v", err)
	}
}

func TestUpdateListFetchError(t *testing.T) {
	originalAPI := gitignoreAPI
	gitignoreAPI = "http://127.0.0.1:1" // nothing listens here
	defer func() { gitignoreAPI = originalAPI }()

	dir := t.TempDir()
	originalPath := environmentsPath
	environmentsPath = filepath.Join(dir, "environments.go")
	defer func() { environmentsPath = originalPath }()

	err := updateList()
	if err == nil {
		t.Fatal("updateList() expected error when the API is unreachable, got nil")
	}
	if !errors.Is(err, err) {
		t.Errorf("updateList() error should wrap the cause, got %v", err)
	}
	if _, statErr := os.Stat(environmentsPath); !os.IsNotExist(statErr) {
		t.Errorf("updateList() should not write the file on fetch error, statErr = %v", statErr)
	}
}
