// Package envlist fetches and renders the gitignore.io environment list
// used to regenerate the embedded snapshot in internal/envs.
package envlist

import (
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

// API is the gitignore.io API base URL. A var so tests can point it at an
// httptest server.
var API = "https://www.gitignore.io/api"

// HTTPClient is the client used for the list fetch. The timeout keeps a hung
// connection from stalling --update-list indefinitely.
var HTTPClient = &http.Client{Timeout: 10 * time.Second}

// Path is the file the generated list is written to, relative to this
// package's directory. Update resolves it against the package source
// location, so running `ignit --update-list` from any working directory
// regenerates the embedded snapshot in internal/envs.
var Path = "environments.go"

// Parse splits the raw comma-separated API response into environment names,
// dropping empty entries.
func Parse(body string) []string {
	var items []string
	for _, raw := range strings.Split(body, ",") {
		if item := strings.TrimSpace(raw); item != "" {
			items = append(items, item)
		}
	}
	return items
}

// Render renders the environments slice as the content of a generated
// environments.go file.
func Render(items []string) string {
	var sb strings.Builder
	sb.WriteString("package envs\n\n")
	sb.WriteString("// Code generated by `ignit -update-list`. DO NOT EDIT.\n")
	sb.WriteString("// Source: https://www.toptal.com/developers/gitignore/api/list\n\n")
	sb.WriteString("// List is a static snapshot of the template list from\n")
	sb.WriteString("// https://github.com/toptal/gitignore.io. The picker works fully\n")
	sb.WriteString("// offline; only writing the .gitignore hits the API.\n")
	sb.WriteString("var List = []string{\n")
	for _, item := range items {
		fmt.Fprintf(&sb, "\t%q,\n", item)
	}
	sb.WriteString("}\n")
	return sb.String()
}

// Write writes the rendered list to path.
func Write(path string, content string) error {
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("failed to write %s: %w", path, err)
	}
	return nil
}

// Fetch calls the gitignore.io list API and parses the result.
func Fetch() ([]string, error) {
	resp, err := HTTPClient.Get(API + "/list")
	if err != nil {
		return nil, fmt.Errorf("failed to list environments: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("failed to list environments: unexpected status %s", resp.Status)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read environments response: %w", err)
	}

	items := Parse(string(body))
	if len(items) == 0 {
		return nil, fmt.Errorf("no environments returned by the API")
	}
	return items, nil
}

// Update fetches the list and regenerates the environments file.
func Update() error {
	items, err := Fetch()
	if err != nil {
		return err
	}

	if err := Write(outputPath(), Render(items)); err != nil {
		return err
	}

	fmt.Printf("Updated %s with %d environments\n", outputPath(), len(items))
	return nil
}

// outputPath resolves the target file for Update: Path is interpreted
// relative to this package's source directory (internal/envlist's parent,
// then internal/envs), so the generated snapshot lands in internal/envs
// no matter the caller's working directory.
func outputPath() string {
	if filepath.IsAbs(Path) {
		return Path
	}
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		// Source path unavailable (unusual build setups): fall back to the
		// working directory so Update still writes somewhere predictable.
		return Path
	}
	pkgDir := filepath.Dir(thisFile)
	return filepath.Join(pkgDir, "..", "envs", Path)
}
