package envlist

import (
	"go/parser"
	"go/token"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"
)

func TestParse(t *testing.T) {
	tests := []struct {
		name string
		body string
		want []string
	}{
		{
			name: "simple list",
			body: "go,rust,python",
			want: []string{"go", "rust", "python"},
		},
		{
			name: "trims whitespace",
			body: " go , rust ,python\n",
			want: []string{"go", "rust", "python"},
		},
		{
			name: "drops empty entries",
			body: "go,,rust,",
			want: []string{"go", "rust"},
		},
		{
			name: "empty body yields nil",
			body: "",
			want: nil,
		},
		{
			name: "whitespace-only body yields nil",
			body: " , , ",
			want: nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := Parse(tt.body)
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("Parse(%q) = %q, want %q", tt.body, got, tt.want)
			}
		})
	}
}

func TestRender(t *testing.T) {
	got := Render([]string{"go", "rust"})

	want := `package envs

// Code generated by ` + "`ignit --update-list`" + `. DO NOT EDIT.
// Source: https://www.toptal.com/developers/gitignore/api/list

// List is a static snapshot of the template list from
// https://github.com/toptal/gitignore.io. The picker works fully
// offline; only writing the .gitignore hits the API.
var List = []string{
	"go",
	"rust",
}
`
	if got != want {
		t.Errorf("Render output mismatch:\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestRenderQuotesSpecialCharacters(t *testing.T) {
	got := Render([]string{"c++", `back` + "`" + `tick`, "quote\"d"})

	// %q must produce valid Go string literals for tricky names.
	for _, literal := range []string{`"c++"`, "\"back`tick\"", `"quote\"d"`} {
		if !strings.Contains(got, "\t"+literal+",\n") {
			t.Errorf("Render output missing %s literal:\n%s", literal, got)
		}
	}
}

func TestRenderOutputParsesAsGo(t *testing.T) {
	src := Render([]string{"go", "c++", "odd\"name"})

	fset := token.NewFileSet()
	if _, err := parser.ParseFile(fset, "environments.go", src, 0); err != nil {
		t.Fatalf("rendered output does not parse as Go: %v", err)
	}
}

func TestWrite(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "environments.go")

	content := Render([]string{"go", "rust"})
	if err := Write(path, content); err != nil {
		t.Fatalf("Write() error = %v", err)
	}

	written, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("failed to read written file: %v", err)
	}
	if string(written) != content {
		t.Errorf("written content mismatch:\ngot:\n%s\nwant:\n%s", written, content)
	}
}

func TestWriteError(t *testing.T) {
	// A directory as target path forces a write error.
	dir := t.TempDir()
	if err := Write(dir, "package envs\n"); err == nil {
		t.Fatal("Write() expected error when target is a directory, got nil")
	}
}

func TestFetch(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/list" {
			http.NotFound(w, r)
			return
		}
		if _, err := w.Write([]byte("go,rust,python")); err != nil {
			t.Errorf("failed to write response: %v", err)
		}
	}))
	defer server.Close()

	originalAPI := API
	API = server.URL
	defer func() { API = originalAPI }()

	items, err := Fetch()
	if err != nil {
		t.Fatalf("Fetch() error = %v", err)
	}
	if !reflect.DeepEqual(items, []string{"go", "rust", "python"}) {
		t.Errorf("Fetch() = %q, want [go rust python]", items)
	}
}

func TestFetchNonOKStatus(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.Error(w, "server error", http.StatusInternalServerError)
	}))
	defer server.Close()

	originalAPI := API
	API = server.URL
	defer func() { API = originalAPI }()

	items, err := Fetch()
	if err == nil {
		t.Fatal("Fetch() expected error for non-200 status, got nil")
	}
	if !strings.Contains(err.Error(), "unexpected status") {
		t.Errorf("Fetch() error = %v, want it to mention unexpected status", err)
	}
	if items != nil {
		t.Errorf("Fetch() items = %q, want nil on error", items)
	}
}

func TestFetchEmptyBody(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if _, err := w.Write([]byte("")); err != nil {
			t.Errorf("failed to write response: %v", err)
		}
	}))
	defer server.Close()

	originalAPI := API
	API = server.URL
	defer func() { API = originalAPI }()

	if _, err := Fetch(); err == nil {
		t.Fatal("Fetch() expected error for empty body, got nil")
	}
}

func TestFetchFailsFastOnHangingServer(t *testing.T) {
	// A server that never answers must not stall Fetch: the client
	// timeout has to turn the hang into an error.
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		select {
		case <-time.After(10 * time.Second):
			if _, err := w.Write([]byte("go,rust")); err != nil {
				t.Errorf("failed to write response: %v", err)
			}
		case <-r.Context().Done(): // client gave up
		}
	}))
	defer server.Close()

	originalAPI, originalClient := API, HTTPClient
	API = server.URL
	HTTPClient = &http.Client{Timeout: 100 * time.Millisecond}
	defer func() { API, HTTPClient = originalAPI, originalClient }()

	start := time.Now()
	if _, err := Fetch(); err == nil {
		t.Fatal("Fetch() expected error against a hanging server, got nil")
	}
	if elapsed := time.Since(start); elapsed > 5*time.Second {
		t.Errorf("Fetch() took %v against a hanging server, want it to fail fast", elapsed)
	}
}

func TestOutputPathResolvesToEnvsDir(t *testing.T) {
	// A relative Path must resolve into internal/envs regardless of the
	// test's working directory.
	got := outputPath()
	if !filepath.IsAbs(got) {
		t.Errorf("outputPath() = %q, want an absolute path", got)
	}
	if want := filepath.Join("internal", "envs", "environments.go"); !strings.HasSuffix(filepath.ToSlash(got), want) {
		t.Errorf("outputPath() = %q, want it to end with %q", got, want)
	}

	// An absolute Path is used verbatim.
	abs := filepath.Join(t.TempDir(), "environments.go")
	original := Path
	Path = abs
	defer func() { Path = original }()
	if got := outputPath(); got != abs {
		t.Errorf("outputPath() with absolute Path = %q, want %q unchanged", got, abs)
	}
}

func TestUpdateEndToEnd(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if _, err := w.Write([]byte("go,rust,python")); err != nil {
			t.Errorf("failed to write response: %v", err)
		}
	}))
	defer server.Close()

	originalAPI := API
	API = server.URL
	defer func() { API = originalAPI }()

	dir := t.TempDir()
	originalPath := Path
	Path = filepath.Join(dir, "environments.go")
	defer func() { Path = originalPath }()

	if err := Update(); err != nil {
		t.Fatalf("Update() error = %v", err)
	}

	written, err := os.ReadFile(Path)
	if err != nil {
		t.Fatalf("failed to read generated file: %v", err)
	}

	want := Render([]string{"go", "rust", "python"})
	if string(written) != want {
		t.Errorf("Update() wrote unexpected content:\ngot:\n%s\nwant:\n%s", written, want)
	}

	// The generated file must parse as valid Go.
	fset := token.NewFileSet()
	if _, err := parser.ParseFile(fset, Path, written, 0); err != nil {
		t.Fatalf("generated file does not parse as Go: %v", err)
	}
}

func TestUpdateFetchError(t *testing.T) {
	originalAPI := API
	API = "http://127.0.0.1:1" // nothing listens here
	defer func() { API = originalAPI }()

	dir := t.TempDir()
	originalPath := Path
	Path = filepath.Join(dir, "environments.go")
	defer func() { Path = originalPath }()

	if err := Update(); err == nil {
		t.Fatal("Update() expected error when the API is unreachable, got nil")
	}
	if _, statErr := os.Stat(Path); !os.IsNotExist(statErr) {
		t.Errorf("Update() should not write the file on fetch error, statErr = %v", statErr)
	}
}
